app/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, MultipleFileField, SelectField, DecimalField, FloatField, HiddenField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import Product, Brand, Category,Translation
from flask_wtf.file import FileField, FileAllowed, FileRequired

class CreateNewProduct(FlaskForm):
    name = StringField('Product Name', validators=[DataRequired(), Length(min=2, max=100)])
    description = TextAreaField('Description', validators=[DataRequired(), Length(min=2)])
    price = DecimalField('Price', validators=[DataRequired()])
    image = FileField('Product Image', validators=[FileAllowed(['jpg', 'png', 'jpeg','webp'])])
    pictures = MultipleFileField('Product Pictures', validators=[FileAllowed(['jpg', 'png', 'jpeg','webp'])])
    instructions = TextAreaField('Instructions')
    ingredients = TextAreaField('Ingredients')
    size = StringField('Size')
    weight = StringField('Weight')
    ean = StringField('EAN')
    category = SelectField('Category', choices=[], coerce=int)   
    subcategory = SelectField('Subcategory', choices=[], coerce=int)
    brand = SelectField('Brand', choices=[], validators=[DataRequired()])
    videos = TextAreaField('Videos')
    submit = SubmitField('Add Product')
    
    def __init__(self, *args, **kwargs):
        super(CreateNewProduct, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name) for category in Category.query.filter_by(parent_id=None).all()]
        self.subcategory.choices = []
    
    def validate_name(self, name):
        product = Product.query.filter_by(name=name.data).first()
        if product:
            raise ValidationError('Product name already exists. Please choose a different name.')
    
    def validate_price(self, price):
        if price.data <= 0:
            raise ValidationError('Price must be greater than zero.')

class EditProduct(FlaskForm):
    name = StringField('Product Name', validators=[DataRequired(), Length(min=2, max=100)])
    description = TextAreaField('Description', validators=[DataRequired(), Length(min=2)])
    price = DecimalField('Price', validators=[DataRequired()])
    image = FileField('Product Image', validators=[FileAllowed(['jpg', 'png', 'jpeg','webp'])])
    pictures = MultipleFileField('Product Pictures', validators=[FileAllowed(['jpg', 'png', 'jpeg','webp'])])
    category = SelectField('Category', choices=[], coerce=int)
    subcategory = SelectField('Subcategory', choices=[], coerce=int)
    instructions = TextAreaField('Instructions')
    ingredients = TextAreaField('Ingredients')
    size = StringField('Size')
    weight = StringField('Weight')
    ean = StringField('EAN')
    brand = SelectField('Brand', choices=[], validators=[DataRequired()])
    videos = TextAreaField('Videos')
    discount = FloatField('Discount (%)')
    submit = SubmitField('Update Product')
    
    def __init__(self, *args, **kwargs):
        super(EditProduct, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name) for category in Category.query.filter_by(parent_id=None).all()]
        self.subcategory.choices = []

    def validate_price(self, price):
        if price.data <= 0:
            raise ValidationError('Price must be greater than zero.')
        
    def validate_discount(self, discount):
        if discount.data < 0:
            raise ValidationError('Discount must be greater than or equal to zero.')

        
class CategoryForm(FlaskForm):
    category = SelectField('Category', choices=[])
    submit = SubmitField('Go')
    
class BrandsForm(FlaskForm):
    brand = SelectField('Brand', choices=[])
    submit = SubmitField('Go')
    
    
class CreateNewBrand(FlaskForm):
    name = StringField('Brand Name')
    summary = TextAreaField('Summary')
    logo = FileField('Brand Logo', validators=[FileAllowed(['jpg', 'png', 'jpeg','webp'])])
    video = FileField('Brand Video', validators=[FileAllowed(['mp4', 'webm'])])
    description = TextAreaField('Description')
    submit = SubmitField('Add Brand')

class EditBrand(FlaskForm):
    name = StringField('Brand Name')
    summary = TextAreaField('Summary')
    logo = FileField('Brand Logo', validators=[FileAllowed(['jpg', 'png', 'jpeg','webp'])])
    video = FileField('Brand Video', validators=[FileAllowed(['mp4', 'webm'])])
    description = TextAreaField('Description')
    submit = SubmitField('Update Brand')


class CreateNewCategory(FlaskForm):
    name = StringField('Category Name')
    parent_id = SelectField('Parent Category', choices=[(0, 'None')], coerce=int)
    submit = SubmitField('Add Category')
    
    def __init__(self, *args, **kwargs):
        super(CreateNewCategory, self).__init__(*args, **kwargs)
        # Populate parent categories (root categories)
        self.parent_id.choices = [(None, 'Root Category')] + [(category.id, category.name) for category in Category.query.filter_by(parent_id=None).all()]

# STRIPE Payment
class CheckoutForm(FlaskForm):
    submit = SubmitField('Proceed to Payment')

# for translation from db
class CreateTranslation(FlaskForm):
    language = SelectField('Language', coerce=str, validators=[DataRequired()])
    field = SelectField('Field', coerce=str, validators=[DataRequired()])
    text= TextAreaField('Text', validators=[DataRequired()])
    product_id = SelectField('Product', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Add Translation')
    
class EditTranslation(FlaskForm):
    language = SelectField('Language', coerce=str, validators=[DataRequired()])
    field = SelectField('Field', coerce=str, validators=[DataRequired()])
    text= TextAreaField('Text', validators=[DataRequired()])
    product_id = SelectField('Product', coerce=int, validators=[DataRequired()])
    submit = SubmitField('Update Translation')



class CreateRatingForm(FlaskForm):
    rating = SelectField('Rating', choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], validators=[DataRequired()])
    review = TextAreaField('Review', validators=[Length(min=0, max=500)])
    product_id = HiddenField('Product ID')
    user_id = HiddenField('User ID')
    submit = SubmitField('Submit')


class UpdateRatingForm(FlaskForm):
    rating = SelectField('Rating', choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], validators=[DataRequired()])
    review = TextAreaField('Review', validators=[Length(min=0, max=500)])
    product_id = HiddenField('Product ID')
    user_id = HiddenField('User ID')
    submit = SubmitField('Submit')
    

app/products/__init__.py
from flask import Blueprint

products = Blueprint('products', __name__)

from . import views
    

app/products/views.py
from inspect import ismethod
from . import products
from flask import render_template, redirect, url_for, request, flash, current_app, session, jsonify
from flask_login import login_user, logout_user, login_required, current_user
from ..decorators import admin_required
from .forms import CreateNewProduct, EditProduct, CategoryForm, BrandsForm, CreateNewBrand, EditBrand, CreateNewCategory, CheckoutForm, CreateTranslation, EditTranslation,CreateRatingForm,UpdateRatingForm
from app.models import Product, Category, Brand, Order, Translation, User, Rating
from app import db
from werkzeug.utils import secure_filename
import os
import json
import stripe
from app.forms import SearchForm
from flask_babel import _  # Add this import
import logging  # Add this import

# Stripe Payment Gateway Start

@products.route('/create-checkout-session', methods=['POST'])
@login_required
def create_checkout_session():
    if request.method != 'POST':
        logging.warning(f"Method {request.method} not allowed for /create-checkout-session")
        return "Method Not Allowed", 405

    form = CheckoutForm()
    if form.validate_on_submit():
        stripe.api_key = current_app.config['STRIPE_SECRET_KEY']
        init_basket()
        basket = session.get("basket", [])
        line_items = []
        for item in basket:
            if isinstance(item, dict) and 'price' in item and 'name' in item and 'quantity' in item:
                price = item['price']
                if item.get('discount'):
                    price = price * (1 - item['discount'] / 100)
                line_items.append({
                    'price_data': {
                        'currency': 'eur',
                        'product_data': {
                            'name': item['name'],
                        },
                        'unit_amount': int(price * 100),
                    },
                    'quantity': item['quantity'],
                })
            else:
                flash(_('Invalid item in basket'), 'error')
                return redirect(url_for('products.basket'))
        try:
            # Create or retrieve the customer
            customer = stripe.Customer.create(
                email=current_user.email,
                name=f"{current_user.firstname} {current_user.lastname}"
            )
            
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=line_items,
                mode='payment',
                success_url=url_for('products.payment_success', _external=True) + '?session_id={CHECKOUT_SESSION_ID}',
                cancel_url=url_for('products.payment_cancel', _external=True),
                customer=customer.id,
                client_reference_id=current_user.id,
                metadata={
                    'user_full_name': f"{current_user.firstname} {current_user.lastname}"
                }
            )
            logging.info(f"Checkout session created: {checkout_session.url}")
            return redirect(checkout_session.url, code=303)
        except Exception as e:
            logging.error(f"Error creating checkout session: {e}")
            return str(e)
    flash(_('Invalid CSRF token'), 'danger')
    return redirect(url_for('products.basket'))


@products.route('/redirect-to-checkout', methods=['GET'])
@login_required
def redirect_to_checkout():
    form = CheckoutForm()
    return render_template('products/redirect_to_checkout.html', form=form)



@products.route('/payment-success')
@login_required
def payment_success():
    flash(_('Payment successful!'), 'success')
    checkout_session_id = request.args.get('session_id')
    if checkout_session_id:
        checkout_session = stripe.checkout.Session.retrieve(checkout_session_id)
        handle_checkout_session(checkout_session)
    session.pop('basket', None)
    return redirect(url_for('auth.profile'))

@products.route('/payment-cancel')
@login_required
def payment_cancel():
    flash(_('Payment canceled.'), 'danger')
    return redirect(url_for('products.basket'))

@products.route('/webhook', methods=['POST'])
def stripe_webhook():
    payload = request.get_data(as_text=True)
    sig_header = request.headers.get('Stripe-Signature')
    endpoint_secret = current_app.config['STRIPE_ENDPOINT_SECRET']
    event = None

    # print("Webhook received")

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
        # print(f"Received event: {event['type']}")
    except ValueError as e:
        # print("Invalid payload")
        return 'Invalid payload', 400
    except stripe.error.SignatureVerificationError as e:
        # print("Invalid signature")
        return 'Invalid signature', 400

    if event['type'] == 'checkout.session.completed':
        checkout_session = event['data']['object']
        # print(f"Checkout session completed: {checkout_session}")
        handle_checkout_session(checkout_session)

    return '', 200

def handle_checkout_session(checkout_session):
    # Retrieve the basket from the session
    basket = session.get("basket", [])
    user_id = checkout_session.get('client_reference_id')
    if not user_id:
        print("User ID not found in checkout session")
        return

    print(f"Processing order for user ID: {user_id}")
    print(f"Checkout session ID: {checkout_session['id']}")
    print(f"Basket contents: {basket}")

    total_amount = sum(
        item['quantity'] * (item['price'] * (1 - item['discount'] / 100)) if item.get('discount') else item['quantity'] * item['price']
        for item in basket
    )
    purchased_products = [{'id':item['id'],'name': item['name'], 'price': item['price'], 'discount': item.get('discount', 0), 'quantity': item['quantity']} for item in basket]

    order = Order(
        payment_id=checkout_session['id'],
        user_id=user_id,
        total_amount=total_amount,
        purchased_products=json.dumps(purchased_products),  # Ensure this is stored as a JSON string
        status='completed'
    )
    db.session.add(order)
    db.session.commit()
    print(f"Order {order.id} added to the database")
    
    
    # Stripe Payment Gateway End

@products.route('/create_new_product', methods=['GET', 'POST'])
@login_required
@admin_required
def create_new_product():
    form = CreateNewProduct()
    brands = db.session.query(Brand).all()
    form.brand.choices = [(brand.name, brand.name) for brand in brands]
    categories = db.session.query(Category).all()
    form.category.choices = [(category.id, category.name) for category in db.session.query(Category).filter_by(parent_id=None).all()]
    form.subcategory.choices = [(subcategory.id, subcategory.name) for category in categories for subcategory in category.subcategories]
    if form.validate_on_submit():
        image = request.files['image']
        if image:
            image_filename = secure_filename(image.filename)
            image.save(os.path.join(current_app.config['PRODUCT_IMAGE_FOLDER'], image_filename))
        pictures = request.files.getlist('pictures')
        picture_filenames = []
        for picture in pictures:
            if picture:
                picture_filename = secure_filename(picture.filename)
                picture.save(os.path.join(current_app.config['PRODUCT_IMAGE_FOLDER'], picture_filename))
                picture_filenames.append(picture_filename)
        brand = db.session.query(Brand).filter_by(name=form.brand.data).first()
        product = Product(name=form.name.data, price=form.price.data, description=form.description.data, image=image_filename, pictures=json.dumps(picture_filenames), instructions=form.instructions.data, ingredients=form.ingredients.data, size=form.size.data, weight=form.weight.data, ean=form.ean.data, category_id=form.category.data, brand=brand,videos=form.videos.data,subcategory_id=form.subcategory.data)
        db.session.add(product)
        db.session.commit()
        flash(_('Product created successfully'), 'success')
        return redirect(url_for('main.index'))
    return render_template('products/create_new_product.html', form=form)


    
def init_basket():
    if "basket" not in session:
        session["basket"] = []
    else:
        # Remove invalid items from the basket
        session["basket"] = [item for item in session["basket"] if isinstance(item, dict) and 'id' in item and 'name' in item and 'price' in item and 'quantity' in item]
        session.modified = True

@products.route("/add_to_basket/<int:id>")
def add_to_basket(id):
    init_basket()
    product = db.session.query(Product).get(id)
    
    if product:
        # Debugging statement to check the contents of session["basket"]
        # print("Basket contents before adding:", session["basket"])
        
        # Check if the product is already in the basket
        for item in session["basket"]:
            if isinstance(item, dict) and int(item["id"]) == int(product.id):
                item["quantity"] = item.get("quantity", 1) + 1
                session.modified = True
                flash(_('From this product, another product was added to the shopping cart'), 'success')
                break
        else:
            # If the product is not in the basket, add it with quantity 1
            session["basket"].append({
                "id": product.id,
                "name": product.name,
                "price": product.price,
                "image": product.image,
                "category_id": product.category_id,
                "brand": product.brand_id,
                "discount": product.get_discount_percent(),
                "quantity": 1
            })
            session.modified = True
            flash(_('Product added to basket'), 'success')
        
        # Debugging statement to check the contents of session["basket"]
        print("Basket contents after adding:")
        for item in session.get("basket", []):

app/templates/products/all_discounted_products.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row d-flex ms-5 justify-content-baseline">
    {% for product in products %}
    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3 position-relative">
      <div class="card shadow-lg mb-5 rounded bg-gradient shine-effect">
        <img
          src="{{ url_for('static', filename='uploads/products/' + product.image) }}"
          class="card-img-top"
          alt="{{ product.name }}"
          style="
            max-height: 250px;
            object-fit: contain;
            background-color: #fcf5f3;
          "
        />
        <div
          class="position-absolute bg-brand text-white p-1 top-0 end-0 shadow rounded-start-top"
        >
          <a
            href="{{ url_for('products.brand', brand_name=product.brand.name) }}"
            class="brand-link"
            >{{ _(product.brand.name) }}</a
          >
        </div>
        <div class="card-header">
          <h5 class="card-title">{{ _(product.name) }}</h5>
          {% set average_rating = product.get_average_rating_for_product(product.id) %}
          {% set average_rating = average_rating if average_rating is not none else 4 %}
          <p class="card-text">
            {% for i in range(1, 6) %}
              <i class="fa fa-star{% if i > average_rating %}-o{% endif %} text-warning"></i>
            {% endfor %}
          </p>
        </div>
        <div class="card-body">
          {% if product.size %}
          <p class="card-text">
            <i class="fa fa-expand text-secondary"></i> {{ _(product.size) }}
          </p>
          {% endif %} {% if product.weight %}
          <p class="card-text">
            <i class="fa fa-weight text-secondary"></i> {{ _(product.weight) }}
          </p>
          {% endif %} {% if product.discount %}
          <p class="card-text">
            <i class="fa fa-percent text-info"></i>
            <span class="badge bg-info text-light"
              >{{ product.get_discount_percent() }}%</span
            >
          </p>
          <p class="card-text">
            <i class="fa fa-euro-sign text-secondary"></i>
            <span class="text-decoration-line-through"
              >{{ product.price }} €</span
            >
            <span class="text-success fs-4"
              >{{ product.get_discount_price() | round(2) }} €</span
            >
          </p>
          {% else %}
          <p class="card-text">
            <i class="fa fa-euro-sign text-secondary"></i> {{ product.price }} €
          </p>
          {% endif %}
          <a
            href="{{ url_for('products.product', id=product.id) }}"
            class="btn btn-light d-flex justify-content-end"
            ><i class="fa fa-info-circle text-danger m-1"></i>
            <span class="badge bg-danger text-light m-1">{{ _('Details') }}</span></a
          >
        </div>
        <div class="card-footer">
          <a
            href="{{ url_for('products.add_to_basket', id=product.id) }}"
            class="btn btn-success"
            data-bs-toggle="tooltip"
            data-bs-placement="top"
            data-bs-title="{{ _('Add to basket') }}"
            ><i class="fa fa-shopping-cart"></i> <i class="fa fa-plus"></i
          ></a>
          {% if current_user.is_administrator() %}
          <a
            href="{{ url_for('products.edit_product', id=product.id) }}"
            data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ _('Update') }} ({{ product.name }})"
            class="btn btn-warning"
            ><i class="fa fa-edit"></i
          ></a>
          <a
            href="{{ url_for('products.delete_product', id=product.id) }}"
            data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ _('Delete') }} ({{ product.name }})"
            class="btn btn-danger"
            onclick="return confirm('{{ _('Are you sure you want to delete') }} {{ product.name }}?')"
            ><i class="fa fa-trash"></i
          ></a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/products/basket.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <!-- loading... -->
  <div id="loader" style="display: none">
    <div class="spinner-grow text-danger" role="status"></div>
    <div class="spinner-grow text-warning" role="status"></div>
    <div class="spinner-grow text-info" role="status"></div>
  </div>
  <!-- end loading... -->
  <div class="row">
    <div class="col-md-12">
      <h1>Your Basket</h1>
      {% if basket|length == 0 %}
      <p>Your basket is empty</p>
      {% else %}
      <table class="table table-striped align-middle">
        <thead>
          <tr>
            <th>Product</th>
            <td>Product Image</td>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>Details</th>
            <th>Actions</th>
            <th>Remove</th>
          </tr>
        </thead>
        <tbody>
          {% for item in basket %}
          <tr>
            <td>{{ item.name }}</td>
            <td class="img-thumbnail">
              <img
                src="{{ url_for('static', filename='uploads/products/' + item.image) }}"
                alt="{{ item.name }}"
                style="
                  width: 150px;
                  height: 150px;
                  border-radius: 50%;
                  object-fit: contain;
                "
                class="img-fluid"
              />
            </td>
            <td>{{ item.quantity }}</td>
            <td>
              {% if item.discount %}
              <del>${{ item.price }}</del>
              <span class="badge bg-danger text-light"
                >-${{ item.discount }} %</span
              >
              <span class="badge bg-success text-light fs-5">
                {{ (item["quantity"] * item["price"] * (1 - item["discount"] /100)) | round(2) }} €
              </span>

              {% else %} ${{ item.price }} {% endif %}
            </td>
            <td>
              {% if item["discount"] %} {{ (item["quantity"] * item["price"] *
              (1 - item["discount"] / 100)) | round(2) }} € {% else %} {{
              (item["quantity"] * item["price"]) | round(2) }} € {% endif %}
            </td>
            <td>
              <a
                href="{{ url_for('products.product', id=item.id) }}"
                class="btn btn-primary"
                ><i class="fa fa-info"></i
              ></a>
            </td>
            <td>
              <a href="{{ url_for('products.increment_product', id=item.id) }}"
                ><i class="fa fa-plus"></i
              ></a>
              <a href="{{ url_for('products.decrement_product', id=item.id) }}"
                ><i class="fa fa-minus"></i
              ></a>
            </td>
            <td>
              <a
                href="{{ url_for('products.remove_from_basket', id=item.id) }}"
                class="btn btn-danger"
                ><i class="fa fa-trash"></i
              ></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="d-flex justify-content-end">
        <h3 class="badge bg-success text-light fs-3 shadow">
          Total: {{ total | round(2) }} €
        </h3>
      </div>
      <!-- Stripe Payment -->
      <div class="d-flex justify-content-end mt-3 mb-5">
        <form action="{{ url_for('products.create_checkout_session') }}" method="POST">
          {{ form.hidden_tag() }}
          <button type="submit" class="btn bg-brand fs-4 text-light"><i class="fa fa-credit-card"></i> Pay Now</button>
        </form>
      </div>
      {% endif %}
    <div class="d-flex justify-content-end">
    <a href="{{ url_for('main.index') }}" class="btn btn-primary"
      ><i class="fa fa-arrow-left"></i> Continue Shopping</a></div>
  </div>
</div>

{% endblock %}

app/templates/products/category.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">{{ _('Home') }}</a></li>
    </ol>
  </nav>
  <!-- loading... -->
  <div id="loader" style="display: none">
    <div class="spinner-grow text-danger" role="status"></div>
    <div class="spinner-grow text-warning" role="status"></div>
    <div class="spinner-grow text-info" role="status"></div>
  </div>
  <!-- end loading... -->
    <!-- All Brands realated to the category -->

    <div class="row d-flex ms-5 justify-content-baseline">
      <!-- All categories in combo box -->
    <div class="col-md-12">
      <form method="post">
        {{ form.hidden_tag() }}
        <div class="input-group mb-3">
            {{ form.category.label(class="input-group-text") }}
            {{ form.category(class="form-select") }}
            <button type="submit" class="btn btn-primary"><i class="fa fa-filter"></i> {{ _('Filter') }}</button>
        </div>
    </form>
      </div>

    {% for product in products %}
    {% if product.category == category %}
    
    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3 position-relative">
      <div class="card shadow-lg  mb-5 rounded bg-gradient shine-effect">
        <img
          src="{{ url_for('static', filename='uploads/products/' + product.image) }}"
          class="card-img-top"
          alt="{{ product.name }}"
          style="max-height: 250px; object-fit: contain; background-color: #fcf5f3"
        />
        <div class="position-absolute bg-brand text-white p-1 top-0 end-0 shadow rounded-start-top"

        >
          <a href="{{ url_for('products.brand', brand_name=product.brand.name) }}"
           class="brand-link"
           >{{ product.brand.name }}</a>
      </div>
        <div class="card-header">
          <h5 class="card-title">{{ product.name }}</h5>
          {% set average_rating = product.get_average_rating_for_product(product.id) %}
          {% set average_rating = average_rating if average_rating is not none else 4 %}
          <p class="card-text">
            {% for i in range(1, 6) %}
              <i class="fa fa-star{% if i > average_rating %}-o{% endif %} text-warning"></i>
            {% endfor %}
          </p>
        </div>
        <div class="card-body">
          {% if product.size %}
          <p class="card-text">
            <i class="fa fa-expand text-secondary"></i> {{ product.size }}
          </p>
          {% endif %}
          {% if product.weight %}
          <p class="card-text">
            <i class="fa fa-weight text-secondary"></i> {{ product.weight }}
          </p>
          {% endif %}
          {% if product.discount %}
          <p class="card-text">
              <i class="fa fa-percent text-info"></i> <span class="badge bg-info text-light">{{ product.get_discount_percent() }}%</span>
          </p>
          <p class="card-text">
              <i class="fa fa-euro-sign text-secondary"></i> 
              <span class="text-decoration-line-through">{{ product.price }} €</span>
              <span class="text-success fs-4">{{ product.get_discount_price() | round(2) }} €</span>
          </p>
      {% else %}
          <p class="card-text">
              <i class="fa fa-euro-sign text-secondary"></i> {{ product.price }} €
          </p>
      {% endif %}
          <a
            href="{{ url_for('products.product', id=product.id) }}"
            class="btn btn-light d-flex justify-content-end"
            ><i class="fa fa-info-circle text-danger m-1"></i>
            <span class="badge bg-danger text-light m-1">{{ _('Details') }}</span></a
          >
        </div>
        <div class="card-footer">
          <a
            href="{{ url_for('products.add_to_basket', id=product.id) }}"
            class="btn btn-success" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ _('Add to basket') }}"
            ><i class="fa fa-shopping-cart"></i> <i class="fa fa-plus"></i></a
          >
          {% if current_user.is_administrator() %}
          <a
            href="{{ url_for('products.edit_product', id=product.id) }}"
            data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ _('Update') }} ({{ product.name }})"
            class="btn btn-warning"
            ><i class="fa fa-edit"></i></a
          >
          <a
            href="{{ url_for('products.delete_product', id=product.id) }}"
            data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ _('Delete') }} ({{ product.name }})"
            class="btn btn-danger"
            onclick="return confirm('{{ _('Are you sure you want to delete') }} {{ product.name }}?')"
            ><i class="fa fa-trash"></i></a
          >
          {% endif %}
        </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
  </div>

  {% set displayed_brands = [] %}
  <hr>
  <div class="row d-flex justify-content-start ">
  {% for product in products %}
      {% if product.category == category and product.brand.name not in displayed_brands %}
              <div class="col-md-1 mb-5 g-2">
                <a href="{{ url_for('products.brand', brand_name=product.brand.name) }}"><img
                  src="{{ url_for('static', filename='uploads/brands/' + product.brand.logo) }}"
                  class="img-fluid rounded-circle ml-5"
                  alt="{{ product.name }}"
                  style="max-height: 200px; max-width: 100px; object-fit: contain;"
              /></a>
              </div>
              {% do displayed_brands.append(product.brand.name) %}
              {% endif %}
              {% endfor %}
            </div>
  </div>

  {% endblock %}

app/templates/products/redirect_to_checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="refresh" content="0;url={{ url_for('products.create_checkout_session') }}" />
</head>
<body>
    <form id="checkoutForm" action="{{ url_for('products.create_checkout_session') }}" method="POST">
        {{ form.hidden_tag() }}
        <noscript>
            <input type="submit" value="Continue to Checkout">
        </noscript>
    </form>
    <script>
        document.getElementById('checkoutForm').submit();
    </script>
</body>
</html>